name = "shellout"
version = "1.7.0-dev"
description = "A Gleam library for cross-platform shell operations"
licences = ["Apache-2.0"]
gleam = ">= 0.34.0"

[repository]
repo = "shellout"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_stdlib = ">= 0.47.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true
