name = "shellout"
version = "1.4.0-dev"
description = "A Gleam library for cross-platform shell operations"
licences = ["Apache-2.0"]
gleam = "~> 0.30"

[repository]
repo = "shellout"
user = "tynanbe"
type = "github"

[[links]]
href = "https://gleam.run/"
title = "Website"

[dependencies]
gleam_stdlib = "~> 0.30"

[dev-dependencies]
gleeunit = "~> 0.11"

[javascript.deno]
allow_env = true
allow_read = true
allow_run = true
